import Provider from "../components/Provider.jsx";
import "./globals.css";

export const metadata = {
  title: "Portfolio Thomas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
